name: Build and deploy to Q
run-name: Build and deploy to ${{ github.event.inputs.environment }}

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: 'MiljÃ¸ det skal deployes til'
        default: 'dev-gcp'
        required: true
        options:
          - 'dev-gcp'
          - 'dev-gcp-q1'
          - 'dev-gcp-experimental'
          - 'dev-gcp-q1-experimental'
jobs:
  tag_build_and_deploy:
    name: 'Build'
    permissions:
      deployments: write
      packages: write
      contents: write
      id-token: write
      security-events: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:

      - name: 'Pull repo'
        uses: actions/checkout@v4

      - name: 'Setter dato og commit variabel'
        run: |
          export TZ=CET

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: 'Setup Node'
        uses: actions/setup-node@v3
        with:
          node-version: 22.x
          registry-url: https://npm.pkg.github.com/
          scope: "@navikt"

      - name: 'Install'
        run: npm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}

      - name: 'Run tests'
        run: npm run test:filtered

      - name: 'Build'
        run: npm run build

      - name: 'Prune - omit dev dependencies'
        run: npm prune --omit=dev

      - uses: nais/docker-build-push@v0
        id: docker-push
        with:
          team: eessipensjon
          tag: ${{ github.event.repository.name }}
          pull: true
          image_suffix: ${{ env.DATE }}${{ env.COMMIT_HASH }} # optional, default empty
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }} # required, but is defined as an organization variable
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }} # required, but is defined as an organization secret

      - uses: nais/login@v0
        with:
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          team: eessipensjon
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ steps.docker-push.outputs.image }}'
          format: 'sarif'
          output: 'trivy.sarif'
          severity: 'HIGH,CRITICAL'
          limit-severities-for-sarif: true

      - name: Upload results to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy.sarif'

      - name: 'Deploy image'
        run: echo "IMAGE=${{ steps.docker-push.outputs.image }}"

      # DEPLOYER TIL NAIS Q
      - name: 'Deploy to NAIS ${{ github.event.inputs.environment }}'
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: nais/${{ github.event.inputs.environment }}.yml
          IMAGE: ${{ steps.docker-push.outputs.image }}
          VARS: nais/${{ github.event.inputs.environment }}-nais-vars.yml

      # OPPRETTER GIT TAG
      - name: 'Opprett git tag'
        run: |
          curl -v -s -X POST https://api.github.com/repos/${{ github.repository }}/git/refs -H "Authorization: token  ${{ secrets.GITHUB_TOKEN }}" -d '{ "ref": "refs/tags/${{ env.DATE }}---${{ env.COMMIT_HASH }}",  "sha": "${{ env.COMMIT_HASH }}" }'

      - name: 'Echo Image Name'
        run: echo "### Image Hash $(echo ${{ steps.docker-push.outputs.image }} | cut -d':' -f2)" >> $GITHUB_STEP_SUMMARY

