name: feature branch push - build, deploy to Q2

on:
  push:
    branches:
      - 'feature/*'

jobs:
  tag_build_and_deploy:
    name: 'Build'
    permissions:
      deployments: write
      packages: write
      contents: write
      id-token: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: 'Pull repo'
        uses: actions/checkout@v4

      - name: 'Setter dato og commit variabel'
        run: |
          export TZ=CET
          echo "DATE=$(date "+%Y-%m-%d--%H-%M-%S")" >> $GITHUB_ENV
          echo "COMMIT_HASH=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: 'Setter Version'
        id: versions
        run: echo "version=${{ env.DATE }}---${{ env.COMMIT_HASH }}" >> $GITHUB_OUTPUT

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: 'Setup Node'
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          registry-url: https://npm.pkg.github.com/
          scope: "@navikt"

      - name: 'Install'
        run: npm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}

      - name: 'Bygg'
        run: npm run build

      - uses: nais/docker-build-push@v0
        id: docker-push
        with:
          team: eessipensjon
          tag: ${{ steps.versions.outputs.version }}
          pull: true
          image_suffix: ${{ env.DATE }}---${{ env.COMMIT_HASH }} # optional, default empty
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }} # required, but is defined as an organization variable
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }} # required, but is defined as an organization secret

      - name: 'Deploy image'
        run: echo "IMAGE=${{ steps.docker-push.outputs.image }}"

      # DEPLOYER TIL NAIS
      - name: 'Deploy to NAIS Q2'
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: nais/dev-gcp.yml
          IMAGE: ${{ steps.docker-push.outputs.image }}
          VARS: nais/dev-gcp-nais-vars.yml

      - name: 'Echo Image Name'
        run: echo "### Image Hash $(echo ${{ steps.docker-push.outputs.image }} | cut -d':' -f2)" >> $GITHUB_STEP_SUMMARY
