name: feature branch push - build, deploy to Q2

on:
  push:
    branches:
      - 'feature/*'

jobs:
  tag_build_and_deploy:
    name: 'Build'
    permissions:
      deployments: write
      packages: write
      contents: write
      id-token: write
      security-events: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: 'Pull repo'
        uses: actions/checkout@v4

      - name: 'Setter dato og commit variabel'
        run: |
          export TZ=CET
          echo "DATE=$(date "+%Y-%m-%d--%H-%M-%S")" >> $GITHUB_ENV
          echo "COMMIT_HASH=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: 'Setter Version'
        id: versions
        run: echo "version=${{ env.DATE }}---${{ env.COMMIT_HASH }}" >> $GITHUB_OUTPUT

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: 'Setup Node'
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          registry-url: https://npm.pkg.github.com/
          scope: "@navikt"

      - name: 'Install'
        run: npm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}

      - name: 'Run tests'
        run: npm run test:filtered

      - name: 'Build'
        run: npm run build

      - name: 'Prune - omit dev dependencies'
        run: npm prune --omit=dev

      - uses: nais/docker-build-push@v0
        id: docker-push
        with:
          team: eessipensjon
          tag: ${{ steps.versions.outputs.version }}
          pull: true
          image_suffix: ${{ env.DATE }}---${{ env.COMMIT_HASH }} # optional, default empty
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }} # required, but is defined as an organization variable
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }} # required, but is defined as an organization secret
      - uses: nais/login@v0
        with:
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          team: eessipensjon
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ steps.docker-push.outputs.image }}'
          format: 'sarif'
          output: 'trivy.sarif'
          severity: 'HIGH,CRITICAL'
          limit-severities-for-sarif: true

      - name: Upload results to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy.sarif'

      - name: 'Deploy image'
        run: echo "IMAGE=${{ steps.docker-push.outputs.image }}"

      # DEPLOYER TIL NAIS
      - name: 'Deploy to NAIS Q2'
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: nais/dev-gcp.yml
          IMAGE: ${{ steps.docker-push.outputs.image }}
          VARS: nais/dev-gcp-nais-vars.yml

      - name: 'Echo Image Name'
        run: echo "### Image Hash $(echo ${{ steps.docker-push.outputs.image }} | cut -d':' -f2)" >> $GITHUB_STEP_SUMMARY

#  trivy-scan:
#    name: Scan docker image med Trivy
#    needs: tag_build_and_deploy
#    runs-on: ubuntu-latest
#    permissions:
#      contents: write # to write sarif
#      security-events: write # push sarif to github security
#      id-token: write # for nais/login
#    steps:
#      - uses: actions/checkout@v4
#      - uses: nais/login@v0
#        with:
#          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
#          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
#          team: eessipensjon
#
#      - name: Pull docker image
#        run: docker pull ${{ needs.tag_build_and_deploy.outputs.image }}
#
#      - name: Run Trivy vulnerability scanner
#        uses: aquasecurity/trivy-action@master
#        with:
#          image-ref: '${{ needs.tag_build_and_deploy.outputs.image }}'
#          format: 'sarif'
#          output: 'trivy.sarif'
#          severity: 'HIGH,CRITICAL'
#          limit-severities-for-sarif: true
#
#      - name: Upload results to GitHub Security
#        uses: github/codeql-action/upload-sarif@v3
#        with:
#          sarif_file: 'trivy.sarif'
