name: Manuell deploy
on:
  repository_dispatch:
    types: [prodsett-command]

jobs:
  deploy_manuelt:
    name: 'Build, push, and deploy'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      # LOGGER VARIABLE
      - name: 'Pull repo'
        uses: actions/checkout@v4
      - run: |
          echo "versjon: ${{ github.event.client_payload.slash_command.arg1 }}"
          echo "cluster: ${{ github.event.client_payload.slash_command.arg2 }}"
          echo "resource: ${{ github.event.client_payload.slash_command.arg2 }}.yml"
          echo "vars: ${{ github.event.client_payload.slash_command.arg2 }}-nais-vars.yml"
          echo "image: europe-north1-docker.pkg.dev/nais-management-233d/eessipensjon/${{ github.event.repository.name }}:${{ github.event.client_payload.slash_command.arg1 }}"

      # DEPLOYER TIL NAIS
      - name: 'Deploy to NAIS'
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: ${{ github.event.client_payload.slash_command.arg2 }}
          RESOURCE: nais/${{ github.event.client_payload.slash_command.arg2 }}.yml
          IMAGE: europe-north1-docker.pkg.dev/nais-management-233d/eessipensjon/${{ github.event.repository.name }}:${{ github.event.client_payload.slash_command.arg1 }}
          VARS: nais/${{ github.event.client_payload.slash_command.arg2 }}-nais-vars.yml

      - name: 'Echo Image Name'
        run: echo "### Image Hash $(echo ${{ steps.docker-push.outputs.image }} | cut -d':' -f2)" >> $GITHUB_STEP_SUMMARY


